site_name: reQ
site_description: HTTP request library for q language
site_url: http://jmcmurray.co.uk/reQ
repo_url: https://github.com/jonathonmcmurray/reQ
theme:
    name: bootstrap
google_analytics: ['UA-119708613-1', 'jmcmurray.co.uk']

